Repository Evilscaught/KaijuCombat, pull requests merged in 2019-11, with the labels that each got.

#2 Evilscaught-Hexenjagd->master
  KaijuCombat/Assets/MenuContainer.cs
  KaijuCombat/Assets/Scenes/DeckBuilderScene.unity
  KaijuCombat/Assets/Scenes/DeckBuilderScene.unity.meta
  KaijuCombat/Assets/Scenes/GameScene.unity
  KaijuCombat/Assets/Scenes/GameScene.unity.meta
  KaijuCombat/Assets/Scenes/MenuScene.unity
  KaijuCombat/Assets/Scenes/MenuScene.unity.meta
  KaijuCombat/Assets/Scripts/MainMenuController.cs
  KaijuCombat/Assets/Scripts/MainMenuController.cs.meta
Labels: bug, enhancement

#4 Request to merge Evilscaught-Hexenjagd branch into master
  KaijuCombat/Assets/Scenes/DeckBuilderScene.unity
  KaijuCombat/Assets/Scripts/DeckBuilderController.cs
  KaijuCombat/Assets/Scripts/DeckBuilderController.cs.meta
  KaijuCombat/Assets/Scripts/MainMenuController.cs
  KaijuCombat/ProjectSettings/EditorBuildSettings.asset
Labels: documentation, enhancement

#5 Test Deck Creator Scene
  KaijuCombat/Assets/LoadDDL.cs
  KaijuCombat/Assets/LoadDDL.cs.meta
  KaijuCombat/Assets/SaveController.cs
  KaijuCombat/Assets/SaveController.cs.meta
  KaijuCombat/Assets/Scenes/CardCreator.unity
  KaijuCombat/Assets/Scenes/CardCreator.unity.meta
  KaijuCombat/Assets/Scenes/MenuScene.unity
  KaijuCombat/Assets/Scenes/TestDeckCreator.unity
  KaijuCombat/Assets/Scenes/TestDeckCreator.unity.meta
  KaijuCombat/Assets/Scripts/manageDeck.cs
  KaijuCombat/Assets/Scripts/manageDeck.cs.meta
  KaijuCombat/Assets/sliderChanges.cs
  KaijuCombat/Assets/sliderChanges.cs.meta
  KaijuCombat/Assets/sliderMusicChange.cs
  KaijuCombat/Assets/sliderMusicChange.cs.meta
Labels: enhancement

#6 Request to merge Evilscaught-Hexenjagd branch into master
  KaijuCombat/Assets/Scenes/TestDeckCreator.unity
  KaijuCombat/Assets/Scripts/Card.cs
  KaijuCombat/Assets/Scripts/Lane.cs
  KaijuCombat/Assets/Scripts/MonsterCard.cs
  KaijuCombat/Assets/Scripts/Player.cs
  KaijuCombat/Assets/Scripts/manageDeck.cs
Labels: documentation

#7 Request to merge Evilscaught-Hexenjagd branch into master: Added Audio
  KaijuCombat/Assets/Audio.meta
  KaijuCombat/Assets/Audio/ClickInitiate.wav
  KaijuCombat/Assets/Audio/ClickInitiate.wav.meta
  KaijuCombat/Assets/Audio/ClickRelease.wav
  KaijuCombat/Assets/Audio/ClickRelease.wav.meta
  KaijuCombat/Assets/Audio/Frontend.mp3.meta
  KaijuCombat/Assets/Audio/GameOver.mp3
  KaijuCombat/Assets/Audio/GameOver.mp3.meta
  KaijuCombat/Assets/Audio/PlopSound1.mp3
  KaijuCombat/Assets/Audio/PlopSound1.mp3.meta
  KaijuCombat/Assets/Audio/PlopSound2.mp3
  KaijuCombat/Assets/Audio/PlopSound2.mp3.meta
  KaijuCombat/Assets/Audio/PlopSound3.mp3
  KaijuCombat/Assets/Audio/PlopSound3.mp3.meta
  KaijuCombat/Assets/Prefabs/AudioManager.prefab
  KaijuCombat/Assets/Prefabs/AudioManager.prefab.meta
  KaijuCombat/Assets/Scenes/DeckBuilderScene.unity
  KaijuCombat/Assets/Scenes/EscapeUI.unity
  KaijuCombat/Assets/Scenes/EscapeUI.unity.meta
  KaijuCombat/Assets/Scenes/GameScene.unity
  KaijuCombat/Assets/Scenes/MenuScene.unity
  KaijuCombat/Assets/Scripts/AudioManager.cs
  KaijuCombat/Assets/Scripts/AudioManager.cs.meta
  KaijuCombat/Assets/Scripts/DeckBuilderController.cs
  KaijuCombat/Assets/Scripts/EscapeUIController.cs
  KaijuCombat/Assets/Scripts/MainMenuController.cs
  KaijuCombat/Assets/Scripts/Sound.cs
  KaijuCombat/Assets/Scripts/Sound.cs.meta
Labels: enhancement
